apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycv
  namespace: mycvproject
spec:
  selector:
    matchLabels:
      run: mycv
  replicas: 1
  template:
    metadata:
      labels:
        run: mycv
    spec:
      containers:
      - name: mycv
        image: shukkoor/myonlinecv
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 200
          periodSeconds: 20
  

